#!/bin/sh

if [ "$(uname -s)" = "Darwin" ]
then
    if [ ! -d "/usr/local/Cellar" ];then
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    brew install ctags cscope
elif [ "$(uname -s)" = "Linux" ]
then
    yum install ctags cscope
else
    sudo apt-get install ctags cscope
fi

chmod +x $(pwd)/upcs 
mkdir -p /usr/local/bin/
ln -s $(pwd)/upcs /usr/local/bin/upcs
ln -s $(pwd)/vimrc ~/.vimrc

git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim -c PluginInstall
