#!/bin/sh                                                                       
find $PWD -name "*.c" -o -name "*.h" > $PWD/cscope.files
cscope -Rbkq -i cscope.files

ctags -R --c++-kinds=+p --fields=+iaS --extra=+q
